kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-deployment
  namespace: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: local-pvcontainer
      volumes:
        - name: local-pvcontainer
          persistentVolumeClaim:
            claimName: local-pvc

