apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/dataMake sure the directory exists inside Minikube:
# Run these commands before running the yaml file 
# minikube ssh
#sudo mkdir -p /mnt/data
#sudo chmod 777 /mnt/data
#exit


    
