kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache

rules:
  - apiGroups: ["*"] #"apps","rbac.authorization.k8s.io","batch"]
    resources: ["*"] #deployment","pod","service"]
    verbs: ["*"] #get","apply","delete","watch","patch"]
    
