apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devopsbatches.wasim.com
spec:
  group: wasim.com
  names:
    plural: devopsbatches
    singular: devopsbatch
    kind: DevOpsBatch
    shortNames:
      - wassam
      - wasim
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "This is devops batch"
                duration:
                  type: string
                  description: "This is devops batch duration"
                mode:
                  type: string
                  description: "This is devops batch mode offline or online"

